name: dev-build

on:
  push:
    branches: [dev]
    paths-ignore:
      - "*.md"
  pull_request:
    branches: [dev, main]

  workflow_dispatch:

jobs:
  build:
    name: Build Comet-Nuget
    env:
      NUPKG_MAJOR: 0.4
      BASE: 334
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "11"

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Install Maui Workload
        shell: pwsh
        run: |
          dotnet workload install android ios maccatalyst macos maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
          Invoke-WebRequest 'https://raw.githubusercontent.com/Samsung/Tizen.NET/main/workload/scripts/workload-install.ps1' -OutFile 'workload-install.ps1';
           .\workload-install.ps1
          dotnet workload list

      - name: Run tests
        run: dotnet test tests/Comet.Tests.Cases/Comet.Tests.Cases.csproj --logger "trx;LogFileName=test-results.trx"

      - uses: dorny/test-reporter@v1
        with:
          name: test-results
          path: "tests/Comet.Tests.Cases/TestResults/test-results.trx"
          reporter: "dotnet-trx"

      - name: Restore Comet-Nuget.sln
        run: dotnet restore build/Comet-Nuget.sln

      - name: Build Comet-Nuget.sln
        run: dotnet msbuild build/Comet-Nuget.sln

      - name: Nuget Pack step
        shell: bash
        run: |
          MINOR_VERSION=$(( $BASE + $GITHUB_RUN_NUMBER ))
          VERSION=$NUPKG_MAJOR.$MINOR_VERSION-alpha
          echo "PACKAGE VERSION: $VERSION"
          nuget pack Comet.nuspec -version $VERSION -Symbols -SymbolPackageFormat snupkg
          nuget pack Comet.Test.nuspec -version $VERSION -Symbols -SymbolPackageFormat snupkg

      - name: Nuget Pack Template step
        shell: bash
        run: |
          MINOR_VERSION=$(( $BASE + $GITHUB_RUN_NUMBER ))
          VERSION=$NUPKG_MAJOR.$MINOR_VERSION-alpha
          echo "PACKAGE VERSION: $VERSION"
          nuget pack "templates\comet-templates.nuspec" -version $VERSION

      - uses: actions/upload-artifact@v2
        name: Upload Nuget Artifact
        with:
          name: nuget-artifact.${{env.GITHUB_RUN_NUMBER}}
          path: |
            **\*.nupkg
            **\*.snupkg
            **\*.symbols.nupkg
