name: dev-build

on:
  push:
    branches: [dev]
    paths-ignore:
      - "*.md"
  pull_request:
    branches: [dev, main]

  workflow_dispatch:

jobs:
  test:
    name: Test Comet
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Maui Workload
        shell: bash
        run: |
          dotnet workload restore build/Comet-Tests.sln
          curl -sSL https://raw.githubusercontent.com/Samsung/Tizen.NET/main/workload/scripts/workload-install.sh | sudo bash
          dotnet workload list

      - name: Run tests
        run: |
          dotnet restore build/Comet-Tests.sln
          dotnet test build/Comet-Tests.sln --logger "trx;LogFileName=test-results.trx"

      - uses: dorny/test-reporter@v1
        with:
          name: test-results
          path: "tests/Comet.Tests.Cases/TestResults/test-results.trx"
          reporter: "dotnet-trx"

  build:
    name: Build Comet-Nuget
    needs: test
    env:
      NUPKG_MAJOR: 0.4
      BASE: 334
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "11"

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Install Maui Workload
        shell: pwsh
        run: |
          & dotnet workload install maui `
            --skip-sign-check `

      - name: Restore Comet-Nuget.sln
        run: msbuild /r build/Comet-Nuget.sln

      - name: Build Comet-Nuget.sln
        run: msbuild build/Comet-Nuget.sln

      - name: Nuget Pack step
        shell: bash
        run: |
          MINOR_VERSION=$(( $BASE + $GITHUB_RUN_NUMBER ))
          VERSION=$NUPKG_MAJOR.$MINOR_VERSION-alpha
          echo "PACKAGE VERSION: $VERSION"
          nuget pack Comet.nuspec -version $VERSION -Symbols -SymbolPackageFormat snupkg

      - name: Nuget Pack Template step
        shell: bash
        run: |
          MINOR_VERSION=$(( $BASE + $GITHUB_RUN_NUMBER ))
          VERSION=$NUPKG_MAJOR.$MINOR_VERSION-alpha
          echo "PACKAGE VERSION: $VERSION"
          nuget pack "templates\comet-templates.nuspec" -version $VERSION

      - uses: actions/upload-artifact@v2
        name: Upload Nuget Artifact
        with:
          name: nuget-artifact.${{env.GITHUB_RUN_NUMBER}}
          path: |
            **\*.nupkg
            **\*.snupkg
            **\*.symbols.nupkg
