name: main-template

#this drops to nuget

on:
  push:
    branches: [main]
    paths:
      - "templates/**"
      - ".github/workflows/main-template.yml"
      - "*.md"

  workflow_dispatch:

jobs:
  build:
    name: Build Template
    env:
      NUPKG_MAJOR: 0.4
      BASE: 334
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Nuget Pack Template step
        shell: bash
        run: |
          MINOR_VERSION=$(( $BASE + $GITHUB_RUN_NUMBER ))
          VERSION=$NUPKG_MAJOR.$MINOR_VERSION-beta
          echo "PACKAGE VERSION: $VERSION"
          nuget pack "templates\comet-templates.nuspec" -version $VERSION

      - uses: actions/upload-artifact@v2
        name: Upload Nuget Artifact
        with:
          name: nuget-artifact
          path: |
            **\*.nupkg
            **\*.snupkg
            **\*.symbols.nupkg

  publish:
    name: Publish
    needs:
      - build
    runs-on: windows-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: nuget-artifact

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: "latest"

      - name: Push nuget to Nuget.org
        run: |
          nuget push nuget-artifact\*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET_API_KEY }} -SkipDuplicate
