name: main-build

#this drops to nuget

on:
  push:
    branches: [main]
    paths-ignore:
      - "templates/**"
      - "*.md"

  workflow_dispatch:

jobs:
  build:
    name: Build Comet-Nuget
    env:
      NUPKG_MAJOR: 0.4
      BASE: 334
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "11"

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Install Maui Workload
        shell: pwsh
        run: |
          dotnet workload install android ios maccatalyst macos maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
          Invoke-WebRequest 'https://raw.githubusercontent.com/Samsung/Tizen.NET/main/workload/scripts/workload-install.ps1' -OutFile 'workload-install.ps1';
           .\workload-install.ps1
          dotnet workload list

      - name: Restore Comet-Nuget.sln
        run: dotnet restore build/Comet-Nuget.sln

      - name: Build Comet-Nuget.sln
        run: dotnet msbuild build/Comet-Nuget.sln

      - name: Nuget Pack step
        shell: bash
        run: |
          MINOR_VERSION=$(( $BASE + $GITHUB_RUN_NUMBER ))
          VERSION=$NUPKG_MAJOR.$MINOR_VERSION-beta
          echo "PACKAGE VERSION: $VERSION"
          nuget pack Comet.nuspec -version $VERSION -Symbols -SymbolPackageFormat snupkg
          nuget pack Comet.Test.nuspec -version $VERSION -Symbols -SymbolPackageFormat snupkg

      - uses: actions/upload-artifact@v2
        name: Upload Nuget Artifact
        with:
          name: nuget-artifact
          path: |
            **\*.nupkg
            **\*.snupkg
            **\*.symbols.nupkg

  publish:
    name: Publish
    needs:
      - build
    runs-on: windows-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: nuget-artifact

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: "latest"

      - name: Push nuget to Nuget.org
        run: |
          nuget push nuget-artifact\*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET_API_KEY }} -SkipDuplicate
