name: test-build

on:
  pull_request:
    branches: [dev, main]

  workflow_dispatch:

jobs:
  build:
    name: Test Comet
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

#       - name: Build Maui to setup the environment
#         working-directory: External/Maui
#         run: |
#           dotnet tool restore
#           dotnet cake --target=VS

      - name: Install Maui Workload
        shell: bash
        run: |
          dotnet workload restore build/Comet-Tests.sln
          curl -sSL https://raw.githubusercontent.com/Samsung/Tizen.NET/main/workload/scripts/workload-install.sh | sudo bash
          dotnet workload list
          
      - name: Run tests
        run: |
          dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
          dotnet nuget list source
          dotnet restore build/Comet-Tests.sln
          dotnet test build/Comet-Tests.sln --logger trx --results-directory "TestResults"

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: Test result
          path: TestResults
